import { useState, useEffect, useRef, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "./AuthContext";
import { useUserData } from "./hooks/useUserData";
import { RG } from "./data/referenceRanges";
import { uploadDocument, validateFile, formatFileSize, getEmojiForType } from "./services/storage";
import { addDocument, updateDocument } from "./services/firestore";

/* ═══ ICONS ═══ */
const S=p=>(<svg width={p.z||20} height={p.z||20} viewBox="0 0 24 24" fill="none" stroke={p.sk||"currentColor"} strokeWidth={p.sw||1.7} strokeLinecap="round" strokeLinejoin="round" style={p.style}>{p.children}</svg>);
const I={
Heart:p=><S {...p}><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></S>,
User:p=><S {...p}><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></S>,
Users:p=><S {...p}><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/></S>,
Act:p=><S {...p}><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></S>,
File:p=><S {...p}><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></S>,
Shield:p=><S {...p}><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></S>,
TUp:p=><S {...p}><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></S>,
TDn:p=><S {...p}><polyline points="23 18 13.5 8.5 8.5 13.5 1 6"/><polyline points="17 18 23 18 23 12"/></S>,
Warn:p=><S {...p}><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></S>,
Ok:p=><S {...p}><polyline points="20 6 9 17 4 12"/></S>,
Dn:p=><S {...p}><polyline points="7 13 12 18 17 13"/><line x1="12" y1="18" x2="12" y2="6"/></S>,
Share:p=><S {...p}><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></S>,
Chv:p=><S {...p}><polyline points="9 18 15 12 9 6"/></S>,
DNA:p=><S {...p}><path d="M2 15c6.667-6 13.333 0 20-6"/><path d="M9 22c1.798-1.998 2.518-3.995 2.807-5.993"/><path d="M15 2c-1.798 1.998-2.518 3.995-2.807 5.993"/><path d="M17 6l-2.5-2.5"/><path d="M7 18l2.5 2.5"/></S>,
Drop:p=><S {...p}><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/></S>,
Spark:p=><S {...p}><path d="m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3L12 3Z"/></S>,
Brain:p=><S {...p}><path d="M12 2a7 7 0 0 0-7 7c0 2.38 1.19 4.47 3 5.74V17a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-2.26c1.81-1.27 3-3.36 3-5.74a7 7 0 0 0-7-7z"/></S>,
Bell:p=><S {...p}><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></S>,
Plus:p=><S {...p}><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></S>,
Scan:p=><S {...p}><path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><line x1="7" y1="12" x2="17" y2="12"/></S>,
Leaf:p=><S {...p}><path d="M11 20A7 7 0 0 1 9.8 6.9C15.5 4.9 17 3.5 17 3.5s1.5 2.5 1.5 7c0 4.5-2.5 7.5-7.5 9.5z"/><path d="M12 20V10"/></S>,
Run:p=><S {...p}><circle cx="12" cy="5" r="2.5"/><path d="M5 22l3-9 4 2 3-7"/><path d="M15 13l3 9"/><path d="M8 13l-3 2"/></S>,
Chat:p=><S {...p}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></S>,
Eye:p=><S {...p}><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></S>,
Pill:p=><S {...p}><path d="m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z"/><path d="m8.5 8.5 7 7"/></S>,
Send:p=><S {...p}><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></S>,
Pulse:p=><S {...p}><path d="M3 12h4l3-9 4 18 3-9h4"/></S>,
Scale:p=><S {...p}><path d="M8 21h8"/><path d="M12 17V3"/><path d="m17 8-5 5-5-5"/></S>,
Ruler:p=><S {...p}><path d="M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.41 2.41 0 0 1 0-3.4l2.6-2.6a2.41 2.41 0 0 1 3.4 0Z"/><path d="m14.5 12.5 2-2"/><path d="m11.5 9.5 2-2"/><path d="m8.5 6.5 2-2"/></S>,
Transfer:p=><S {...p}><path d="M18 8L22 12L18 16"/><path d="M2 12H22"/><path d="M6 16L2 12L6 8"/></S>,
Watch:p=><S {...p}><rect x="5" y="2" width="14" height="20" rx="7" ry="7"/><path d="M12 9v3l1.5 1.5"/></S>,
Steps:p=><S {...p}><path d="M4 16c0-1.1.9-2 2-2h1a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z"/><path d="M14 5c0-1.1.9-2 2-2h1a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2z"/><path d="M6.5 14L16 5"/></S>,
Sleep:p=><S {...p}><path d="M2 4h4l3 12h10"/><path d="M17 8h4"/><path d="M19 6v4"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10"/></S>,
Oxy:p=><S {...p}><path d="M2 12a5 5 0 0 1 5-5c3 0 4 2 5 2s2-2 5-2a5 5 0 0 1 5 5c0 6-10 10-10 10S2 18 2 12z"/></S>,
Lock:p=><S {...p}><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></S>,
Key:p=><S {...p}><path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"/></S>,
Link:p=><S {...p}><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></S>,
QR:p=><S {...p}><rect x="2" y="2" width="8" height="8" rx="1"/><rect x="14" y="2" width="8" height="8" rx="1"/><rect x="2" y="14" width="8" height="8" rx="1"/><path d="M14 14h2v2h-2z"/><path d="M20 14h2v2h-2z"/><path d="M14 20h2v2h-2z"/><path d="M20 20h2v2h-2z"/><path d="M17 17h2v2h-2z"/></S>,
Copy:p=><S {...p}><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></S>,
LogOut:p=><S {...p}><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></S>,
};

/* ═══ DATA — Demo data comes from useUserData hook ═══ */
const IC_MAP = { Leaf: I.Leaf, Run: I.Run, Eye: I.Eye, Pill: I.Pill };

/* ═══ THEME ═══ */
const C={bg:"#F4F5F9",bg2:"#EAECF2",card:"#FFFFFF",glass:"rgba(255,255,255,0.8)",brd:"#DFE2EB",brd2:"#CDD1DE",tx:"#0F1117",tx2:"#555970",tx3:"#8E93A8",pri:"#4F6AE8",priL:"#EEF1FD",priS:"#D0D8FA",priD:"#3548B0",dan:"#E5484D",danL:"#FFF0F0",danS:"#FECDD3",wrn:"#FF8B3E",wrnL:"#FFF5ED",wrnS:"#FFE0C2",suc:"#30A46C",sucL:"#ECFDF5",sucS:"#BBF7D0",pur:"#7C66DC",purL:"#F5F2FF",pnk:"#E93D82",pnkL:"#FFF0F6",blu:"#0091FF",bluL:"#E8F4FF"};

/* ═══ SHARED ═══ */
const Bd=({s,t})=>{const m={g:{bg:C.sucL,c:C.suc,bd:C.sucS},w:{bg:C.wrnL,c:C.wrn,bd:C.wrnS},r:{bg:C.danL,c:C.dan,bd:C.danS},b:{bg:C.priL,c:C.pri,bd:C.priS},p:{bg:C.purL,c:C.pur,bd:"#E4DEFF"}};const st=m[s]||m.b;return <span style={{background:st.bg,color:st.c,border:`1px solid ${st.bd}`,padding:"2px 9px",borderRadius:20,fontSize:10,fontWeight:700,display:"inline-flex",alignItems:"center"}}>{t}</span>};
const Sk=({data,color=C.pri,w=70,h=20})=>{if(!data?.length)return null;const mn=Math.min(...data)*0.9,mx=Math.max(...data)*1.1,r=mx-mn||1;const pts=data.map((v,i)=>`${(i/(data.length-1))*w},${h-((v-mn)/r)*h}`).join(" ");return <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} style={{overflow:"visible"}}><polyline points={pts} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity="0.8"/><circle cx={w} cy={h-((data[data.length-1]-mn)/r)*h} r="2.5" fill="white" stroke={color} strokeWidth="2"/></svg>};
const Ch=({data,dk,rng,color})=>{const W=440,H=150,pL=40,pR=14,pT=18,pB=28,iW=W-pL-pR,iH=H-pT-pB;const vs=data.map(d=>d[dk]),all=[...vs,rng.n,rng.x],dN=Math.min(...all)*0.85,dX=Math.max(...all)*1.15,rr=dX-dN||1;const tX=i=>pL+(i/(data.length-1))*iW,tY=v=>pT+iH-((v-dN)/rr)*iH;const pts=vs.map((v,i)=>`${tX(i)},${tY(v)}`).join(" ");const ar=`${tX(0)},${tY(vs[0])} ${pts} ${tX(vs.length-1)},${pT+iH} ${tX(0)},${pT+iH}`;return <svg width="100%" viewBox={`0 0 ${W} ${H}`} style={{height:"auto"}}><defs><linearGradient id={`cg${dk}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity="0.14"/><stop offset="100%" stopColor={color} stopOpacity="0"/></linearGradient></defs><rect x={pL} y={tY(rng.x)} width={iW} height={Math.max(0,tY(rng.n)-tY(rng.x))} fill={C.suc} opacity={0.05} rx={4}/><line x1={pL} y1={tY(rng.x)} x2={pL+iW} y2={tY(rng.x)} stroke={C.suc} strokeWidth="1" strokeDasharray="5,5" opacity={0.2}/><line x1={pL} y1={tY(rng.n)} x2={pL+iW} y2={tY(rng.n)} stroke={C.suc} strokeWidth="1" strokeDasharray="5,5" opacity={0.2}/><polygon points={ar} fill={`url(#cg${dk})`}/><polyline points={pts} fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>{vs.map((v,i)=><g key={i}><circle cx={tX(i)} cy={tY(v)} r="4" fill="white" stroke={color} strokeWidth="2"/><text x={tX(i)} y={tY(v)-9} textAnchor="middle" fill={color} fontSize="9.5" fontWeight="700">{v}</text></g>)}{data.map((d,i)=><text key={i} x={tX(i)} y={H-4} textAnchor="middle" fill={C.tx3} fontSize="9">{d.d}</text>)}</svg>};
const TV=({ms,cn,onS,sl})=>(<div style={{position:"relative",width:"100%",paddingBottom:"55%"}}><svg style={{position:"absolute",inset:0,width:"100%",height:"100%"}} viewBox="0 0 100 100">{cn.map(([f,t],i)=>{const a=ms.find(m=>m.id===f),b=ms.find(m=>m.id===t);if(!a||!b)return null;const mid=(a.y+b.y)/2;return <path key={i} d={`M${a.x} ${a.y+3}C${a.x} ${mid},${b.x} ${mid},${b.x} ${b.y-3}`} stroke={C.brd2} strokeWidth="0.35" fill="none" strokeDasharray={a.gn===0?"1.5,1.5":"none"}/>})}{ms.map(m=>{const iS=sl===m.id,gc={0:"#9498AD",1:C.pur,2:C.pri,3:C.pnk},bc=m.me?C.pri:gc[m.gn]||C.pri;return <g key={m.id} onClick={()=>onS(m.id)} style={{cursor:"pointer"}}><circle cx={m.x} cy={m.y} r={m.me?4.5:3.2} fill={iS?bc:"white"} stroke={bc} strokeWidth={iS?0.8:0.5}/>{m.me&&<circle cx={m.x} cy={m.y} r="6" fill="none" stroke={bc} strokeWidth="0.25" opacity="0.5"><animate attributeName="r" values="5.5;7.5;5.5" dur="3s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.5;0;0.5" dur="3s" repeatCount="indefinite"/></circle>}<text x={m.x} y={m.y+(m.gn===3?7:-6)} textAnchor="middle" fill={iS?bc:C.tx} fontSize="2.3" fontWeight={m.me||iS?"700":"500"}>{m.nm}</text><text x={m.x} y={m.y+(m.gn===3?9.5:-3.5)} textAnchor="middle" fill={C.tx3} fontSize="1.5">{m.rl}</text>{m.co.length>0&&<circle cx={m.x+3.5} cy={m.y-2.5} r="1.1" fill={C.wrn}/>}</g>})}</svg></div>);
const Cd=({children,style,onClick})=>(<div onClick={onClick} style={{background:C.card,borderRadius:16,border:`1px solid ${C.brd}`,boxShadow:"0 1px 4px rgba(0,0,0,0.03)",...style}}>{children}</div>);
const RB=({pct,color})=>(<div style={{width:"100%",height:5,borderRadius:3,background:C.bg2}}><div style={{width:`${pct}%`,height:"100%",borderRadius:3,background:`linear-gradient(90deg,${color}66,${color})`}}/></div>);
const Ring=({pct,color,sz=44,sw=4})=>{const r=(sz-sw)/2,circ=2*Math.PI*r;return <svg width={sz} height={sz} style={{transform:"rotate(-90deg)"}}><circle cx={sz/2} cy={sz/2} r={r} fill="none" stroke={C.bg2} strokeWidth={sw}/><circle cx={sz/2} cy={sz/2} r={r} fill="none" stroke={color} strokeWidth={sw} strokeLinecap="round" strokeDasharray={circ} strokeDashoffset={circ*(1-Math.min(pct,100)/100)}/></svg>};

/* ═══ OTP Component ═══ */
const OTPShare=({onClose})=>{
  const[code]=useState(()=>String(Math.floor(100000+Math.random()*900000)));
  const[sec,setSec]=useState(10);
  const[copied,setCopied]=useState(false);
  useEffect(()=>{if(sec<=0){onClose();return}const t=setInterval(()=>setSec(s=>s-1),1000);return()=>clearInterval(t)},[sec,onClose]);
  return <div style={{textAlign:"center",padding:"8px 0"}}>
    <div style={{width:56,height:56,borderRadius:18,background:`linear-gradient(135deg,${C.pri}15,${C.pur}15)`,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 12px"}}><I.Key z={26} style={{color:C.pri}}/></div>
    <p style={{fontSize:12,color:C.tx2,marginBottom:16}}>C&oacute;digo de verificaci&oacute;n temporal</p>
    <div style={{display:"flex",justifyContent:"center",gap:6,marginBottom:12}}>{code.split("").map((d,i)=><div key={i} style={{width:40,height:50,borderRadius:12,background:C.bg,border:`2px solid ${C.pri}30`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,fontWeight:900,color:C.tx,fontFamily:"'JetBrains Mono',monospace"}}>{d}</div>)}</div>
    <div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,marginBottom:16}}>
      <div style={{position:"relative",width:28,height:28}}><Ring pct={(sec/10)*100} color={sec<=3?C.dan:C.pri} sz={28} sw={3}/><span style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:800,color:sec<=3?C.dan:C.pri}}>{sec}</span></div>
      <span style={{fontSize:12,color:sec<=3?C.dan:C.tx3,fontWeight:600}}>segundos restantes</span>
    </div>
    <button onClick={()=>{navigator.clipboard?.writeText(code);setCopied(true)}} style={{display:"flex",alignItems:"center",gap:6,margin:"0 auto",padding:"8px 20px",borderRadius:12,fontSize:12,fontWeight:700,color:copied?C.suc:C.pri,background:copied?C.sucL:C.priL,border:`1px solid ${copied?C.sucS:C.priS}`,cursor:"pointer"}}>{copied?<I.Ok z={13} style={{color:C.suc}}/>:<I.Copy z={13} style={{color:C.pri}}/>}{copied?"Copiado":"Copiar c\u00f3digo"}</button>
  </div>
};

/* ═══ APP ═══ */
export default function App(){
  const{t,i18n}=useTranslation();
  const{onboardingData,handleLogout,user}=useAuth();
  const userData=useUserData();
  const{profile:realProfile,documents:realDocs,isEmpty,isDemo,demo}=userData;
  // Resolve data: use real data when available, demo data as fallback
  const U=realProfile||demo.profile;
  const WEAR=demo.wear;
  const TM=isEmpty.family?demo.family:userData.familyMembers;
  const CN=isEmpty.family?demo.connections:userData.connections;
  const HR=isEmpty.family?demo.risks:userData.hereditaryRisks;
  const BL=isEmpty.labs?demo.labs:userData.labResults;
  const INS=isEmpty.labs?demo.insights:userData.insights;
  const DC=demo.docs;
  const TIPS_DATA=demo.tips.map(t=>({...t,ic:IC_MAP[t.icKey]||I.Leaf}));
  const CHAT_INIT=demo.chatInit;
  const AI_R=demo.aiResponses;
  const[tab,sT]=useState("d");
  const[uploading,setUploading]=useState(false);
  const[uploadProg,setUploadProg]=useState(0);
  const[uploadType,setUploadType]=useState("Otro");
  const fileRef=useRef(null);const[bio,sB]=useState("ir");const[fam,sF]=useState("me");const[mod,sM]=useState(null);const[exp,sE]=useState(null);const[an,sA]=useState(false);const[msgs,setMsgs]=useState(CHAT_INIT);const[inp,setInp]=useState("");const[tipCat,setTC]=useState("all");const chatRef=useRef(null);
  const[dismissed,setDismissed]=useState(()=>{try{return JSON.parse(localStorage.getItem("hg_dismissed_tips")||"[]")}catch{return[]}});
  const dismiss=(id)=>{const next=[...dismissed,id];setDismissed(next);localStorage.setItem("hg_dismissed_tips",JSON.stringify(next))};
  const od=onboardingData||{};
  const tips=[];
  if(!od.selectedIntegrations||od.selectedIntegrations.length===0)tips.push({id:"devices",icon:"⌚",color:C.pri,title:"Conecta un dispositivo",desc:"Sincroniza tu wearable para obtener datos en tiempo real y mejores recomendaciones."});
  if(!od.familyConditions||od.familyConditions.length===0)tips.push({id:"family",icon:"👨‍👩‍👧",color:C.pur,title:"Completa tu historial familiar",desc:"Registra datos de padres, hermanos e hijos para detectar patrones hereditarios."});
  tips.push({id:"docs",icon:"📄",color:C.suc,title:"Sube documentos médicos",desc:"Centraliza tus analíticas, informes y recetas en un solo lugar seguro."});
  const activeTips=tips.filter(t=>!dismissed.includes(t.id));
  useEffect(()=>{sA(false);const t=setTimeout(()=>sA(true),60);return()=>clearTimeout(t)},[tab]);
  useEffect(()=>{if(chatRef.current)chatRef.current.scrollTop=chatRef.current.scrollHeight},[msgs]);
  const closeOTP=useCallback(()=>sM(null),[]);
  const mem=TM.find(m=>m.id===fam),lat=BL[BL.length-1],ac=an?"opacity-100 translate-y-0":"opacity-0 translate-y-3";
  const tabs=[{id:"d",l:t("nav.home"),ic:I.Heart},{id:"f",l:t("nav.family"),ic:I.DNA},{id:"e",l:t("nav.data"),ic:I.Act},{id:"a",l:t("nav.ai"),ic:I.Chat},{id:"t",l:t("nav.tips"),ic:I.Leaf},{id:"o",l:t("nav.docs"),ic:I.File},{id:"p",l:t("nav.profile"),ic:I.User}];
  const alertCount=INS.filter(i=>i.ur!=="low").length;
  const sendMsg=(text)=>{if(!text.trim())return;setMsgs(p=>[...p,{r:"user",t:text}]);setInp("");setTimeout(()=>{const resp=AI_R[text]||`Analizo tu pregunta sobre "${text}"...\n\nBasado en tu perfil, te recomiendo consultar con tu m\u00e9dico para una valoraci\u00f3n personalizada.\n\n\u26a0\ufe0f *Informaci\u00f3n orientativa.*`;setMsgs(p=>[...p,{r:"ai",t:resp},{r:"sug",t:null,opts:["\u00bfPor qu\u00e9 baja mi hierro?","\u00bfRiesgos para Sof\u00eda?","\u00bfQu\u00e9 comer esta semana?","\u00bfMi sue\u00f1o es suficiente?"]}])},700)};

  /* HOME */
  const Dash=()=>{const oob=Object.entries(RG).filter(([k])=>k!=="wt").filter(([k,r])=>lat[k]<r.n||lat[k]>r.x);const ok=Object.entries(RG).filter(([k])=>k!=="wt").filter(([k,r])=>lat[k]>=r.n&&lat[k]<=r.x);
  return <div className={`sy5 ${ac}`} style={{transition:"all 0.5s"}}>
    {isDemo&&<div style={{padding:"8px 14px",borderRadius:12,background:`linear-gradient(135deg,${C.wrnL},${C.wrnS}40)`,border:`1px solid ${C.wrnS}`,display:"flex",alignItems:"center",gap:8}}><I.Eye z={14} style={{color:C.wrn}}/><p style={{fontSize:11,fontWeight:600,color:C.wrn}}>{t("demo.banner")}</p></div>}
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><p style={{fontSize:12,color:C.tx3,fontWeight:500}}>{t("dash.greeting")}</p><h1 style={{fontSize:24,fontWeight:900,color:C.tx,letterSpacing:-0.5}}>{realProfile?.firstName||U.name.split(" ")[0]}</h1></div><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{position:"relative",cursor:"pointer"}} onClick={()=>sT("a")}><I.Bell z={20} style={{color:C.tx3}}/>{alertCount>0&&<span style={{position:"absolute",top:-3,right:-3,width:15,height:15,borderRadius:8,background:C.dan,color:"white",fontSize:8,fontWeight:800,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 2px 4px ${C.dan}40`}}>{alertCount}</span>}</div><div onClick={()=>sT("p")} style={{width:38,height:38,borderRadius:13,background:`linear-gradient(135deg,${C.pri},${C.pur})`,display:"flex",alignItems:"center",justifyContent:"center",color:"white",fontSize:13,fontWeight:800,cursor:"pointer",boxShadow:`0 4px 12px ${C.pri}35`}}>{realProfile?.firstName?realProfile.firstName.charAt(0).toUpperCase():"C"}{realProfile?.firstName?"":" M"}</div></div></div>
    {/* Smart Tips */}
    {activeTips.length>0&&<div style={{display:"flex",gap:7,overflowX:"auto",paddingBottom:2}}>{activeTips.map(tip=><div key={tip.id} style={{minWidth:220,flexShrink:0,padding:"12px 14px",borderRadius:14,background:`linear-gradient(135deg,${tip.color}08,${tip.color}15)`,border:`1px solid ${tip.color}25`,position:"relative"}}><button onClick={()=>dismiss(tip.id)} style={{position:"absolute",top:8,right:8,background:"none",border:"none",cursor:"pointer",fontSize:14,color:C.tx3,lineHeight:1}}>×</button><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><span style={{fontSize:18}}>{tip.icon}</span><span style={{fontSize:12,fontWeight:800,color:C.tx}}>{tip.title}</span></div><p style={{fontSize:11,color:C.tx2,lineHeight:1.4}}>{tip.desc}</p></div>)}</div>}
    {/* Blockchain ID */}
    <Cd style={{padding:"10px 14px",cursor:"pointer",background:`linear-gradient(135deg,${C.card},${C.priL})`,border:`1px solid ${C.priS}`}} onClick={()=>sM("otp")}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:34,height:34,borderRadius:10,background:`${C.pri}12`,display:"flex",alignItems:"center",justifyContent:"center"}}><I.QR z={16} style={{color:C.pri}}/></div><div style={{flex:1}}><p style={{fontSize:9,color:C.tx3,fontWeight:600,textTransform:"uppercase",letterSpacing:0.8}}>ID Blockchain Personal</p><p style={{fontSize:14,fontWeight:800,color:C.tx,fontFamily:"'JetBrains Mono',monospace",letterSpacing:1}}>{realProfile?.bid||U.bid}</p></div><div style={{padding:"5px 10px",borderRadius:8,background:C.pri,display:"flex",alignItems:"center",gap:3}}><I.Share z={11} sk="white"/><span style={{fontSize:10,fontWeight:700,color:"white"}}>Compartir</span></div></div></Cd>
    {/* Vitals */}
    <div style={{display:"flex",gap:7,overflowX:"auto",paddingBottom:2}}>{[{l:"Altura",v:`${realProfile?.h||U.h}cm`,ic:I.Ruler,cl:C.pri},{l:"Peso",v:`${realProfile?.w||U.w}kg`,ic:I.Scale,cl:C.pur},{l:"Pulso",v:`${realProfile?.hr||U.hr}bpm`,ic:I.Pulse,cl:C.dan},{l:"Tensi\u00f3n",v:realProfile?.bp||U.bp,ic:I.Heart,cl:C.suc},{l:"SpO2",v:`${realProfile?.sp02||U.sp02}%`,ic:I.Oxy,cl:C.blu},{l:"Sangre",v:realProfile?.bl||U.bl,ic:I.Drop,cl:C.pnk}].map((s,i)=><Cd key={i} style={{padding:"9px 12px",minWidth:88,flexShrink:0}}><div style={{display:"flex",alignItems:"center",gap:4,marginBottom:4}}><s.ic z={12} style={{color:s.cl}}/><span style={{fontSize:9,color:C.tx3,fontWeight:600,textTransform:"uppercase",letterSpacing:0.4}}>{s.l}</span></div><span style={{fontSize:16,fontWeight:800,color:C.tx}}>{s.v}</span></Cd>)}</div>
    {/* Wearables */}
    <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><h2 style={{fontSize:15,fontWeight:800,color:C.tx,display:"flex",alignItems:"center",gap:5}}><I.Watch z={15} style={{color:C.pur}}/>Wearables</h2><span style={{fontSize:10,color:C.tx3,fontWeight:500}}>Hoy, en directo</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:7}}>{Object.entries(WEAR).map(([k,w])=>{const pct=Math.min((w.v/w.g)*100,100);return <Cd key={k} style={{padding:"10px",textAlign:"center"}}><div style={{position:"relative",width:42,height:42,margin:"0 auto 5px"}}><Ring pct={pct} color={w.cl} sz={42} sw={3.5}/><span style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:800,color:w.cl}}>{k==="sleep"?w.v:Math.round(pct)}%</span></div><p style={{fontSize:12,fontWeight:800,color:C.tx}}>{typeof w.v==="number"&&w.v>=1000?(w.v/1000).toFixed(1)+"k":w.v}</p><p style={{fontSize:9,color:C.tx3,fontWeight:500}}>{w.l}</p><p style={{fontSize:8,color:C.tx3,opacity:0.6}}>{w.src}</p></Cd>})}</div></div>
    {/* Alerts */}
    {alertCount>0&&<Cd style={{padding:"12px 14px",cursor:"pointer",borderLeft:`3px solid ${C.dan}`,background:`linear-gradient(90deg,${C.danL},${C.card})`}} onClick={()=>sT("a")}><div style={{display:"flex",alignItems:"center",gap:10}}><I.Spark z={17} style={{color:C.dan}}/><div style={{flex:1}}><p style={{fontSize:13,fontWeight:800,color:C.dan}}>{alertCount} alertas IA</p><p style={{fontSize:11,color:C.tx2}}>Hierro &middot; Vit C &middot; Colesterol</p></div><I.Chv z={14} style={{color:C.dan,opacity:0.4}}/></div></Cd>}
    {/* OOB */}
    {oob.length>0&&<div><h2 style={{fontSize:15,fontWeight:800,color:C.tx,marginBottom:8}}>Requieren atenci&oacute;n</h2>{oob.map(([k,r])=>{const v=lat[k],lo=v<r.n,prev=BL[BL.length-2]?.[k],diff=prev?(((v-prev)/prev)*100).toFixed(1):null;return <Cd key={k} style={{padding:"12px 14px",marginBottom:7,cursor:"pointer",borderLeft:`3px solid ${C.dan}`}} onClick={()=>{sB(k);sT("e")}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:5,marginBottom:3}}><span style={{fontSize:12,fontWeight:700,color:C.tx}}>{r.l}</span><Bd s="r" t={lo?"Bajo":"Alto"}/></div><div style={{display:"flex",alignItems:"baseline",gap:3}}><span style={{fontSize:22,fontWeight:900,color:C.dan}}>{v}</span><span style={{fontSize:10,color:C.tx3}}>{r.u}</span>{diff&&<span style={{fontSize:10,fontWeight:700,color:C.dan,marginLeft:4}}>{Number(diff)>0?"+":""}{diff}%</span>}</div></div><Sk data={BL.map(d=>d[k])} color={C.dan} w={60} h={24}/></div></Cd>})}</div>}
    {/* OK */}
    <div><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><h2 style={{fontSize:15,fontWeight:800,color:C.tx}}>En rango</h2><button onClick={()=>sT("e")} style={{fontSize:11,fontWeight:700,color:C.pri,background:"none",border:"none",cursor:"pointer"}}>Todo &rarr;</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}>{ok.map(([k,r])=><Cd key={k} style={{padding:"10px 12px",cursor:"pointer"}} onClick={()=>{sB(k);sT("e")}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:10,color:C.tx3,fontWeight:600}}>{r.l}</span><Bd s="g" t="OK"/></div><div style={{display:"flex",alignItems:"end",justifyContent:"space-between"}}><span style={{fontSize:18,fontWeight:900,color:C.suc}}>{lat[k]}<span style={{fontSize:9,color:C.tx3,marginLeft:2}}>{r.u}</span></span><Sk data={BL.map(d=>d[k])} color={C.suc} w={42} h={14}/></div></Cd>)}</div></div>
    {/* Family quick + hereditary */}
    <div><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><h2 style={{fontSize:15,fontWeight:800,color:C.tx}}>Familia</h2><button onClick={()=>sT("f")} style={{fontSize:11,fontWeight:700,color:C.pri,background:"none",border:"none",cursor:"pointer"}}>&Aacute;rbol &rarr;</button></div><div style={{display:"flex",gap:6,overflowX:"auto",marginBottom:8}}>{TM.filter(m=>["p1","p2","me","s1","c1"].includes(m.id)).map(m=><div key={m.id} onClick={()=>{sF(m.id);sT("f")}} style={{textAlign:"center",cursor:"pointer",flexShrink:0,minWidth:50}}><div style={{width:38,height:38,borderRadius:12,background:m.me?`linear-gradient(135deg,${C.pri}18,${C.pur}18)`:C.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:17,margin:"0 auto",border:m.me?`2px solid ${C.pri}`:`1px solid ${C.brd}`}}>{m.av}</div><p style={{fontSize:9,fontWeight:m.me?700:500,color:m.me?C.pri:C.tx2,marginTop:3}}>{m.nm.split(" ")[0]}</p></div>)}</div>{HR.slice(0,2).map((h,i)=><Cd key={i} style={{padding:"10px 14px",marginBottom:6,cursor:"pointer"}} onClick={()=>sT("f")}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><I.DNA z={13} style={{color:h.c}}/><span style={{flex:1,fontSize:12,fontWeight:700,color:C.tx}}>{h.p}</span><span style={{fontSize:12,fontWeight:800,color:h.c}}>{h.risk}%</span></div><RB pct={h.risk} color={h.c}/></Cd>)}</div>
  </div>};

  /* FAMILY */
  const Fam=()=><div className={`sy4 ${ac}`} style={{transition:"all 0.5s"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{fontSize:20,fontWeight:900,color:C.tx}}>&Aacute;rbol Familiar</h2><button onClick={()=>sM("add")} style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:10,fontSize:11,fontWeight:700,color:"white",border:"none",cursor:"pointer",background:`linear-gradient(135deg,${C.pri},${C.pur})`}}><I.Plus z={11} sk="white"/>A&ntilde;adir</button></div>
    <Cd style={{overflow:"hidden",padding:0}}><div style={{padding:"8px 14px 0",display:"flex",gap:12,fontSize:10,color:C.tx3}}>{[{c:"#9498AD",l:"Abuelos"},{c:C.pur,l:"Padres"},{c:C.pri,l:"T\u00fa"},{c:C.pnk,l:"Hijos"}].map((x,i)=><span key={i} style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:6,height:6,borderRadius:3,background:x.c}}/>{x.l}</span>)}</div><TV ms={TM} cn={CN} onS={sF} sl={fam}/></Cd>
    {mem&&<Cd style={{padding:14}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}><div style={{width:44,height:44,borderRadius:14,background:mem.me?`linear-gradient(135deg,${C.pri}12,${C.pur}12)`:C.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,border:mem.me?`2px solid ${C.pri}`:`1px solid ${C.brd}`}}>{mem.av}</div><div style={{flex:1}}><h3 style={{fontSize:16,fontWeight:800,color:C.tx}}>{mem.nm}</h3><p style={{fontSize:11,color:C.tx2}}>{mem.rl} &middot; {mem.ag}{typeof mem.ag==="string"?"":" a\u00f1os"} &middot; <span style={{color:C.dan,fontWeight:700}}>{mem.bl}</span></p></div></div>{mem.co.length>0?<div style={{display:"flex",flexWrap:"wrap",gap:5}}>{mem.co.map((c,i)=><span key={i} style={{padding:"3px 9px",borderRadius:8,fontSize:11,background:C.wrnL,color:C.wrn}}>{c}</span>)}</div>:<p style={{fontSize:11,color:C.tx3,fontStyle:"italic"}}>Sin condiciones</p>}</Cd>}
    <h3 style={{fontSize:15,fontWeight:800,color:C.tx}}>Patrones Hereditarios</h3>
    {HR.map((h,i)=><Cd key={i} style={{overflow:"hidden"}}><button style={{width:"100%",padding:"11px 14px",textAlign:"left",display:"flex",alignItems:"center",gap:8,background:"none",border:"none",cursor:"pointer"}} onClick={()=>sE(exp===`h${i}`?null:`h${i}`)}><div style={{width:30,height:30,borderRadius:9,background:`${h.c}12`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><I.DNA z={13} style={{color:h.c}}/></div><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:13,fontWeight:700,color:C.tx}}>{h.p}</span><span style={{fontSize:10,fontWeight:800,color:h.c}}>{h.risk}%</span></div><p style={{fontSize:10,color:C.tx3}}>{h.m.join(" \u2192 ")}</p></div><I.Chv z={13} style={{color:C.tx3,transform:exp===`h${i}`?"rotate(90deg)":"none",transition:"transform 0.2s"}}/></button>{exp===`h${i}`&&<div style={{padding:"0 14px 12px"}}><RB pct={h.risk} color={h.c}/><div style={{borderRadius:10,padding:10,background:C.bg,marginTop:6}}><p style={{fontSize:11,color:C.tx2,lineHeight:1.5}}>{h.i}</p></div></div>}</Cd>)}
  </div>;

  /* EVOLUTION */
  const Evo=()=>{const r=RG[bio],v=lat[bio],f=BL[0][bio],cg=(((v-f)/f)*100).toFixed(1),lo=v<r.n,hi=v>r.x,oo=lo||hi,clr=oo?C.dan:C.suc;
  return <div className={`sy4 ${ac}`} style={{transition:"all 0.5s"}}>
    <h2 style={{fontSize:20,fontWeight:900,color:C.tx}}>Evoluci&oacute;n</h2>
    <div style={{display:"flex",gap:5,overflowX:"auto"}}>{Object.entries(RG).map(([k,rr])=>{const vv=lat[k],o2=vv<rr.n||vv>rr.x,at=bio===k;return <button key={k} onClick={()=>sB(k)} style={{flexShrink:0,padding:"6px 12px",borderRadius:10,fontSize:11,fontWeight:at?700:500,cursor:"pointer",background:at?C.pri:C.card,color:at?"white":C.tx2,border:`1px solid ${at?C.pri:o2?C.danS:C.brd}`,boxShadow:at?`0 2px 8px ${C.pri}35`:"none"}}>{o2&&!at&&<span style={{display:"inline-block",width:5,height:5,borderRadius:3,background:C.dan,marginRight:3}}/>}{rr.l}</button>})}</div>
    <Cd style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:13,color:C.tx2,fontWeight:600}}>{r.l}</span><Bd s={oo?"r":"g"} t={lo?"Bajo":hi?"Alto":"Normal"}/></div><div style={{display:"flex",alignItems:"baseline",gap:5}}><span style={{fontSize:38,fontWeight:900,color:C.tx,letterSpacing:-1.5}}>{v}</span><span style={{fontSize:13,color:C.tx3}}>{r.u}</span><span style={{fontSize:13,fontWeight:800,color:clr,marginLeft:8}}>{Number(cg)>0?"+":""}{cg}%</span></div><p style={{fontSize:11,color:C.tx3,marginTop:3}}>Rango: {r.n}&ndash;{r.x} {r.u}</p></Cd>
    <Cd style={{padding:"12px 8px"}}><Ch data={BL} dk={bio} rng={r} color={clr}/></Cd>
    <Cd style={{overflow:"hidden"}}>{Object.entries(RG).map(([k,rr],i)=>{const vv=lat[k],ff=BL[0][k],pc=(((vv-ff)/ff)*100).toFixed(1),o2=vv<rr.n||vv>rr.x;return <div key={k} onClick={()=>sB(k)} style={{display:"flex",alignItems:"center",gap:6,padding:"9px 14px",cursor:"pointer",borderTop:i>0?`1px solid ${C.brd}`:"none",background:bio===k?C.priL:"transparent"}}><span style={{fontSize:11,color:C.tx,flex:1,fontWeight:bio===k?700:500}}>{rr.l}</span><Sk data={BL.map(d=>d[k])} color={o2?C.dan:C.suc} w={38} h={12}/><span style={{fontSize:12,fontWeight:700,color:o2?C.dan:C.suc,width:36,textAlign:"right"}}>{vv}</span><span style={{fontSize:10,fontWeight:600,width:44,textAlign:"right",color:Number(pc)<0?(k==="ch"?C.suc:C.dan):(k==="ch"?C.dan:C.suc)}}>{Number(pc)>0?"+":""}{pc}%</span></div>})}</Cd>
  </div>};

  /* AI CHAT */
  const AiChat=()=><div style={{display:"flex",flexDirection:"column",height:"calc(100vh - 120px)",transition:"all 0.5s"}} className={ac}>
    <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><div style={{width:34,height:34,borderRadius:11,background:`linear-gradient(135deg,${C.pri},${C.pur})`,display:"flex",alignItems:"center",justifyContent:"center"}}><I.Spark z={15} sk="white"/></div><div><h2 style={{fontSize:17,fontWeight:800,color:C.tx}}>Asistente IA</h2><p style={{fontSize:9.5,color:C.tx3}}>Informativo &middot; Consulta siempre tu m&eacute;dico</p></div></div>
    <div ref={chatRef} style={{flex:1,overflowY:"auto",display:"flex",flexDirection:"column",gap:8,paddingBottom:8}}>
      {msgs.map((m,i)=>{
        if(m.r==="ai")return <div key={i} style={{maxWidth:"88%",padding:"11px 14px",borderRadius:"4px 14px 14px 14px",background:C.card,border:`1px solid ${C.brd}`,boxShadow:"0 1px 3px rgba(0,0,0,0.03)"}}><div style={{display:"flex",alignItems:"center",gap:4,marginBottom:5}}><I.Spark z={10} style={{color:C.pri}}/><span style={{fontSize:9,fontWeight:700,color:C.pri}}>HealthGen IA</span></div><div style={{fontSize:12,color:C.tx2,lineHeight:1.55,whiteSpace:"pre-wrap"}} dangerouslySetInnerHTML={{__html:m.t.replace(/\*\*(.*?)\*\*/g,'<b style="color:#0F1117">$1</b>')}}></div></div>;
        if(m.r==="user")return <div key={i} style={{maxWidth:"80%",padding:"9px 14px",borderRadius:"14px 14px 4px 14px",background:`linear-gradient(135deg,${C.pri},${C.priD})`,color:"white",fontSize:12.5,alignSelf:"flex-end",boxShadow:`0 2px 8px ${C.pri}30`}}>{m.t}</div>;
        if(m.r==="sug")return <div key={i} style={{display:"flex",flexWrap:"wrap",gap:5}}>{m.opts.map((o,j)=><button key={j} onClick={()=>sendMsg(o)} style={{padding:"6px 12px",borderRadius:20,fontSize:11,fontWeight:600,color:C.pri,background:C.priL,border:`1px solid ${C.priS}`,cursor:"pointer"}}>{o}</button>)}</div>;
        return null;
      })}
    </div>
    <div style={{display:"flex",gap:6,padding:"6px 0"}}><input value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendMsg(inp)} placeholder="Pregunta sobre tu salud..." style={{flex:1,padding:"9px 14px",borderRadius:12,border:`1.5px solid ${C.brd}`,background:C.card,fontSize:12.5,color:C.tx,outline:"none"}}/><button onClick={()=>sendMsg(inp)} style={{width:40,height:40,borderRadius:12,border:"none",cursor:"pointer",background:`linear-gradient(135deg,${C.pri},${C.pur})`,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 2px 8px ${C.pri}30`}}><I.Send z={15} sk="white"/></button></div>
  </div>;

  /* TIPS */
  const Tips=()=>{const filtered=tipCat==="all"?TIPS_DATA:TIPS_DATA.filter(t=>t.cat===tipCat);return <div className={`sy4 ${ac}`} style={{transition:"all 0.5s"}}>
    <div style={{display:"flex",alignItems:"center",gap:6}}><I.Leaf z={18} style={{color:C.suc}}/><h2 style={{fontSize:20,fontWeight:900,color:C.tx}}>Recomendaciones</h2></div>
    <Cd style={{padding:"10px 14px",background:C.sucL,border:`1px solid ${C.sucS}`}}><p style={{fontSize:11,color:C.tx2}}>Sugerencias basadas en tus datos. <b style={{color:C.suc}}>Consulta siempre tu m&eacute;dico.</b></p></Cd>
    <div style={{display:"flex",gap:5,overflowX:"auto"}}>{[{id:"all",l:"Todo"},{id:"diet",l:"\ud83e\udd57 Dieta"},{id:"exercise",l:"\ud83c\udfc3 Ejercicio"},{id:"natural",l:"\ud83c\udf3f Natural"},{id:"meds",l:"\ud83d\udc8a Medicaci\u00f3n"}].map(c=><button key={c.id} onClick={()=>setTC(c.id)} style={{flexShrink:0,padding:"6px 12px",borderRadius:10,fontSize:11,fontWeight:tipCat===c.id?700:500,cursor:"pointer",background:tipCat===c.id?C.pri:C.card,color:tipCat===c.id?"white":C.tx2,border:`1px solid ${tipCat===c.id?C.pri:C.brd}`}}>{c.l}</button>)}</div>
    {filtered.map((tip,i)=><Cd key={i} style={{padding:14}}><div style={{display:"flex",alignItems:"start",gap:10}}><div style={{width:36,height:36,borderRadius:11,background:`${tip.cl}10`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><tip.ic z={16} style={{color:tip.cl}}/></div><div style={{flex:1}}><h3 style={{fontSize:13,fontWeight:700,color:C.tx}}>{tip.title}</h3><p style={{fontSize:11,color:C.tx2,marginTop:2,lineHeight:1.4}}>{tip.desc}</p><div style={{display:"flex",gap:4,marginTop:6,flexWrap:"wrap"}}>{tip.tags.map((t,j)=><span key={j} style={{padding:"2px 8px",borderRadius:20,fontSize:9.5,fontWeight:600,background:`${tip.cl}0d`,color:tip.cl}}>{t}</span>)}</div></div></div></Cd>)}
  </div>};

  /* DOCS */
  const Doc=()=><div className={`sy4 ${ac}`} style={{transition:"all 0.5s"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{fontSize:20,fontWeight:900,color:C.tx}}>Documentos</h2><button onClick={()=>sM("upload")} style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:10,fontSize:11,fontWeight:700,color:"white",border:"none",cursor:"pointer",background:`linear-gradient(135deg,${C.pri},${C.pur})`}}><I.Plus z={11} sk="white"/>Subir</button></div>
    <Cd style={{padding:20,textAlign:"center",cursor:"pointer",border:`2px dashed ${C.priS}`,background:C.priL}} onClick={()=>sM("upload")}><I.Scan z={26} style={{color:C.pri,opacity:0.4,margin:"0 auto 6px"}}/><p style={{fontSize:13,fontWeight:700,color:C.tx}}>Subir documentos</p><p style={{fontSize:11,color:C.tx3,marginTop:3}}>IA extrae datos autom&aacute;ticamente</p></Cd>
    {uploading&&<Cd style={{padding:"12px 14px"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><I.Scan z={14} style={{color:C.pri}}/><span style={{fontSize:12,fontWeight:700,color:C.pri}}>Subiendo... {uploadProg}%</span></div><RB pct={uploadProg} color={C.pri}/></Cd>}
    {realDocs.length>0?realDocs.map(d=><Cd key={d.id} style={{padding:"10px 14px"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:17,width:36,height:36,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:10,background:C.bg}}>{d.emoji||"📄"}</span><div style={{flex:1,minWidth:0}}><p style={{fontSize:12.5,fontWeight:700,color:C.tx,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{d.name}</p><div style={{display:"flex",alignItems:"center",gap:5,marginTop:2}}><span style={{fontSize:10.5,color:C.tx3}}>{d.date||"—"}</span>{d.size&&<span style={{fontSize:10,color:C.tx3}}>{d.size}</span>}{d.aiStatus==="complete"?<Bd s="g" t="IA ✓"/>:d.aiStatus==="analyzing"?<Bd s="b" t="Analizando..."/>:<Bd s="b" t="Subido"/>}</div></div></div></Cd>):DC.map(d=><Cd key={d.id} style={{padding:"10px 14px"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:17,width:36,height:36,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:10,background:C.bg}}>{d.e}</span><div style={{flex:1,minWidth:0}}><p style={{fontSize:12.5,fontWeight:700,color:C.tx,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{d.n}</p><div style={{display:"flex",alignItems:"center",gap:5,marginTop:2}}><span style={{fontSize:10.5,color:C.tx3}}>{d.dt}</span><Bd s="b" t="Demo"/></div></div></div></Cd>)}
    <input ref={fileRef} type="file" accept=".pdf,.jpg,.jpeg,.png" style={{display:"none"}} onChange={async(e)=>{const file=e.target.files?.[0];if(!file||!user)return;const v=validateFile(file);if(!v.valid){alert(v.error);return;}setUploading(true);setUploadProg(0);try{const{path,downloadUrl}=await uploadDocument(user.uid,file,(p)=>setUploadProg(p));const now=new Date();await addDocument(user.uid,{name:file.name.replace(/\.[^.]+$/,""),emoji:getEmojiForType(uploadType||"Otro"),type:uploadType||"Otro",date:`${now.getDate().toString().padStart(2,"0")}/${(now.getMonth()+1).toString().padStart(2,"0")}/${now.getFullYear().toString().slice(-2)}`,size:formatFileSize(file.size),storageUrl:path,downloadUrl,mimeType:file.type,aiAnalysis:null,aiStatus:"pending"});sM(null)}catch(err){alert("Error al subir: "+err.message)}finally{setUploading(false);setUploadProg(0);if(fileRef.current)fileRef.current.value=""}}}/>
  </div>;

  /* PROFILE */
  const Prof=()=><div className={`sy4 ${ac}`} style={{transition:"all 0.5s"}}>
    <Cd style={{padding:20,textAlign:"center",background:`linear-gradient(135deg,${C.priL},${C.purL})`}}><div style={{width:58,height:58,borderRadius:19,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,fontWeight:800,color:"white",background:`linear-gradient(135deg,${C.pri},${C.pur})`,boxShadow:`0 6px 16px ${C.pri}30`}}>{realProfile?.firstName?realProfile.firstName.charAt(0).toUpperCase():"CM"}</div><h2 style={{fontSize:20,fontWeight:900,color:C.tx,marginTop:8}}>{realProfile?.name||U.name}</h2><p style={{fontSize:12,color:C.tx2}}>{realProfile?.age||U.age} a&ntilde;os &middot; {realProfile?.h||U.h}cm &middot; {realProfile?.w||U.w}kg</p><div style={{marginTop:6,display:"inline-flex",gap:6}}><span style={{padding:"3px 12px",borderRadius:20,background:C.danL,fontSize:12,fontWeight:800,color:C.dan}}>{realProfile?.bl||U.bl}</span>{(realProfile?.bmi||U.bmi)&&<span style={{padding:"3px 12px",borderRadius:20,background:C.bg,fontSize:12,fontWeight:600,color:C.tx2}}>IMC {realProfile?.bmi||U.bmi}</span>}</div></Cd>
    {/* Blockchain ID card */}
    <Cd style={{padding:"12px 14px",background:`linear-gradient(135deg,${C.card},${C.priL})`,border:`1.5px solid ${C.priS}`}}><div style={{display:"flex",alignItems:"center",gap:10}}><I.Link z={16} style={{color:C.pri}}/><div style={{flex:1}}><p style={{fontSize:9,color:C.tx3,fontWeight:600,textTransform:"uppercase",letterSpacing:0.8}}>Blockchain ID</p><p style={{fontSize:13,fontWeight:800,color:C.tx,fontFamily:"'JetBrains Mono',monospace",letterSpacing:1}}>{realProfile?.bid||U.bid}</p></div><button onClick={()=>sM("otp")} style={{padding:"5px 10px",borderRadius:8,fontSize:10,fontWeight:700,color:"white",background:C.pri,border:"none",cursor:"pointer"}}>Compartir</button></div></Cd>
    {/* Connected devices */}
    <Cd style={{padding:"12px 14px"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><I.Watch z={14} style={{color:C.pur}}/><h3 style={{fontSize:13,fontWeight:700,color:C.tx}}>Dispositivos conectados</h3></div><div style={{display:"flex",flexDirection:"column",gap:6}}>{[{n:"Apple Watch Series 9",s:"Conectado",cl:C.suc},{n:"iPhone 15 Pro",s:"Conectado",cl:C.suc},{n:"Withings Scale",s:"Desconectado",cl:C.tx3}].map((d,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:4,background:d.cl}}/><span style={{fontSize:12,color:C.tx,flex:1}}>{d.n}</span><span style={{fontSize:10,color:d.cl,fontWeight:600}}>{d.s}</span></div>)}</div></Cd>
    {[{t:"Alergias",ic:I.Warn,it:realProfile?.al||U.al,cl:C.wrn,bg:C.wrnL},{t:"Condiciones",ic:I.Eye,it:realProfile?.co||U.co,cl:C.dan,bg:C.danL},{t:"Vacunas",ic:I.Shield,it:realProfile?.va||U.va,cl:C.suc,bg:C.sucL},{t:"Medicación",ic:I.Pill,it:realProfile?.meds||U.meds,cl:C.pnk,bg:C.pnkL}].map((s,i)=><Cd key={i} style={{padding:"12px 14px"}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:8}}><s.ic z={14} style={{color:s.cl}}/><h3 style={{fontSize:13,fontWeight:700,color:C.tx}}>{s.t}</h3></div><div style={{display:"flex",flexWrap:"wrap",gap:5}}>{s.it.map((x,j)=><span key={j} style={{padding:"3px 10px",borderRadius:7,fontSize:11,background:s.bg,color:s.cl}}>{x}</span>)}</div></Cd>)}
    {[{l:"Compartir con m\u00e9dico",d:"C\u00f3digo OTP temporal",ic:I.Key,cl:C.pri,act:()=>sM("otp")},{l:"Transferir a hijo/a (18+)",d:"Traspaso completo de historial",ic:I.Transfer,cl:C.pnk},{l:"A\u00f1adir familiar",d:"Hijos, padres o hermanos",ic:I.Users,cl:C.pur,act:()=>sM("add")},{l:"Exportar historial",d:"PDF, FHIR o HL7",ic:I.File,cl:C.blu}].map((b,i)=><Cd key={i} style={{padding:"11px 14px",cursor:"pointer"}} onClick={b.act||undefined}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:34,height:34,borderRadius:11,background:C.bg,display:"flex",alignItems:"center",justifyContent:"center"}}><b.ic z={15} style={{color:b.cl}}/></div><div style={{flex:1}}><p style={{fontSize:12,fontWeight:700,color:C.tx}}>{b.l}</p><p style={{fontSize:10,color:C.tx3}}>{b.d}</p></div><I.Chv z={13} style={{color:C.tx3,opacity:0.3}}/></div></Cd>)}
    <Cd style={{padding:"10px 14px",background:C.sucL,border:`1px solid ${C.sucS}`}}><div style={{display:"flex",alignItems:"center",gap:8}}><I.Shield z={15} style={{color:C.suc}}/><div><p style={{fontSize:11,fontWeight:700,color:C.suc}}>Datos protegidos</p><p style={{fontSize:10,color:C.tx2}}>Cifrado E2E &middot; Blockchain &middot; GDPR &middot; HIPAA</p></div></div></Cd>
    {/* Language Toggle */}
    <Cd style={{padding:"12px 14px"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:16}}>🌐</span><div style={{flex:1}}><p style={{fontSize:12,fontWeight:700,color:C.tx}}>Idioma / Language</p></div><div style={{display:"flex",gap:4}}>{[{code:"es",label:"ES"},{code:"en",label:"EN"}].map(lng=><button key={lng.code} onClick={()=>i18n.changeLanguage(lng.code)} style={{padding:"4px 12px",borderRadius:8,fontSize:11,fontWeight:i18n.language?.startsWith(lng.code)?700:500,cursor:"pointer",background:i18n.language?.startsWith(lng.code)?C.pri:"transparent",color:i18n.language?.startsWith(lng.code)?"white":C.tx2,border:`1px solid ${i18n.language?.startsWith(lng.code)?C.pri:C.brd}`}}>{lng.label}</button>)}</div></div></Cd>
    <button onClick={handleLogout} style={{width:"100%",padding:"12px 0",borderRadius:14,fontSize:13,fontWeight:700,color:C.dan,background:C.danL,border:`1px solid ${C.danS}`,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:8,transition:"all 0.15s"}}><I.LogOut z={15} style={{color:C.dan}}/>{t("common.logout")}</button>
  </div>;

  const pg={d:Dash,f:Fam,e:Evo,a:AiChat,t:Tips,o:Doc,p:Prof},P=pg[tab]||Dash;
  return (<div style={{minHeight:"100vh",display:"flex",justifyContent:"center",background:`linear-gradient(180deg,${C.bg},${C.bg2})`,fontFamily:"'Plus Jakarta Sans',-apple-system,sans-serif"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@700;800;900&display=swap');*{margin:0;padding:0;box-sizing:border-box;font-family:'Plus Jakarta Sans',-apple-system,sans-serif;-webkit-font-smoothing:antialiased}.sy4>*+*{margin-top:12px}.sy5>*+*{margin-top:16px}.translate-y-0{transform:translateY(0)}.translate-y-3{transform:translateY(12px)}.opacity-0{opacity:0}.opacity-100{opacity:1}button{outline:none}::-webkit-scrollbar{display:none}input::placeholder{color:${C.tx3}}`}</style>
    <div style={{width:"100%",maxWidth:430,display:"flex",flexDirection:"column",minHeight:"100vh",position:"relative"}}>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 16px 4px",position:"sticky",top:0,zIndex:20,background:`linear-gradient(180deg,${C.bg},${C.bg}dd)`}}><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:28,height:28,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",background:`linear-gradient(135deg,${C.pri},${C.pur})`,boxShadow:`0 2px 6px ${C.pri}30`}}><I.Heart z={13} sk="white" sw={2.2}/></div><span style={{fontSize:13,fontWeight:900,color:C.tx}}>Health<span style={{color:C.pri}}>Gen</span></span></div><div style={{display:"flex",alignItems:"center",gap:4}}><I.Lock z={12} style={{color:C.suc,opacity:0.5}}/><span style={{fontSize:8.5,fontWeight:700,color:C.suc,opacity:0.5}}>BLOCKCHAIN</span></div></div>
      <div style={{flex:1,overflowY:"auto",padding:"4px 16px 90px"}}><P/></div>
      <div style={{position:"absolute",bottom:0,left:0,right:0,padding:"3px 7px 5px",background:`linear-gradient(180deg,transparent,${C.bg}bb 15%,${C.bg} 45%)`}}>
        <div style={{borderRadius:20,display:"flex",padding:2,background:C.glass,border:`1px solid ${C.brd}`,backdropFilter:"blur(20px)",boxShadow:"0 -1px 20px rgba(0,0,0,0.04)"}}>
          {tabs.map(t=>{const at=tab===t.id;return <button key={t.id} onClick={()=>sT(t.id)} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",padding:"6px 0 2px",borderRadius:16,border:"none",cursor:"pointer",position:"relative",background:at?C.priL:"transparent",transition:"all 0.15s"}}>{at&&<div style={{position:"absolute",top:-1,left:"50%",transform:"translateX(-50%)",width:18,height:2.5,borderRadius:2,background:`linear-gradient(90deg,${C.pri},${C.pur})`}}/>}<t.ic z={15} style={{color:at?C.pri:C.tx3}}/><span style={{marginTop:1,fontSize:8,fontWeight:at?800:500,color:at?C.pri:C.tx3}}>{t.l}</span></button>})}
        </div>
      </div>
      {/* MODALS */}
      {mod&&<div style={{position:"absolute",inset:0,zIndex:50,display:"flex",alignItems:"flex-end",background:"rgba(0,0,0,0.2)",backdropFilter:"blur(4px)"}} onClick={()=>sM(null)}>
        <div style={{width:"100%",borderRadius:"22px 22px 0 0",padding:20,background:"white",display:"flex",flexDirection:"column",gap:12,maxHeight:"75vh",overflowY:"auto"}} onClick={e=>e.stopPropagation()}>
          <div style={{width:36,height:4,borderRadius:2,background:C.brd,margin:"0 auto"}}/>
          {mod==="upload"&&<><h3 style={{fontSize:18,fontWeight:900,color:C.tx,textAlign:"center"}}>Subir Documento</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}>{[{l:"Anal\u00edtica",e:"\ud83e\ude78"},{l:"Radiograf\u00eda",e:"\ud83e\uddb4"},{l:"MRI/TAC",e:"\ud83e\udde0"},{l:"Informe",e:"\ud83d\udccb"},{l:"Receta",e:"\ud83d\udc8a"},{l:"Oftalm.",e:"\ud83d\udc41\ufe0f"},{l:"Dermat.",e:"\ud83e\udee3"},{l:"Otro",e:"\ud83d\udcc4"}].map((t,i)=><button key={i} onClick={()=>setUploadType(t.l)} style={{borderRadius:12,padding:12,display:"flex",alignItems:"center",gap:8,background:uploadType===t.l?C.priL:C.bg,border:`1px solid ${uploadType===t.l?C.priS:C.brd}`,cursor:"pointer"}}><span style={{fontSize:18}}>{t.e}</span><span style={{fontSize:12,fontWeight:600,color:C.tx}}>{t.l}</span></button>)}</div><button onClick={()=>fileRef.current?.click()} style={{width:"100%",padding:"11px 0",borderRadius:12,fontSize:13,fontWeight:700,color:"white",border:"none",cursor:"pointer",background:`linear-gradient(135deg,${C.pri},${C.pur})`}}>Seleccionar archivo</button></>}
          {mod==="add"&&<><h3 style={{fontSize:18,fontWeight:900,color:C.tx,textAlign:"center"}}>A&ntilde;adir Familiar</h3><p style={{fontSize:11,color:C.tx3,textAlign:"center"}}>La IA analizar&aacute; patrones hereditarios</p>{[{l:"Hijo/a",d:"Desde reci\u00e9n nacido. Crea su historial desde el d\u00eda 1.",e:"\ud83d\udc76",cl:C.pnk},{l:"Padre/Madre",d:"Datos de padres para patrones hereditarios.",e:"\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67",cl:C.pur},{l:"Hermano/a",d:"Comparte patrones gen\u00e9ticos.",e:"\ud83d\udc6b",cl:C.blu}].map((t,i)=><button key={i} style={{borderRadius:14,padding:14,display:"flex",alignItems:"center",gap:10,background:C.bg,border:`1px solid ${C.brd}`,cursor:"pointer",textAlign:"left",width:"100%"}}><span style={{fontSize:26,width:44,height:44,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:12,background:`${t.cl}10`}}>{t.e}</span><div><p style={{fontSize:13,fontWeight:700,color:C.tx}}>{t.l}</p><p style={{fontSize:10.5,color:C.tx3,marginTop:1}}>{t.d}</p></div></button>)}<div style={{borderRadius:10,padding:10,background:C.sucL,border:`1px solid ${C.sucS}`}}><p style={{fontSize:10.5,color:C.tx2}}><b style={{color:C.suc}}>Transferencia 18+:</b> Al cumplir 18, transfiere el historial completo a su propia cuenta HealthGen.</p></div></>}
          {mod==="otp"&&<><h3 style={{fontSize:18,fontWeight:900,color:C.tx,textAlign:"center"}}>Compartir con M&eacute;dico</h3><p style={{fontSize:11,color:C.tx3,textAlign:"center"}}>Tu ID: <b style={{fontFamily:"'JetBrains Mono',monospace",color:C.tx}}>{realProfile?.bid||U.bid}</b></p><OTPShare onClose={closeOTP}/><div style={{borderRadius:10,padding:10,background:C.bg}}><p style={{fontSize:10.5,color:C.tx2,lineHeight:1.4}}>El m&eacute;dico introduce tu <b>Blockchain ID</b> + este <b>c&oacute;digo de 6 d&iacute;gitos</b> para acceder temporalmente a tu historial. El acceso expira autom&aacute;ticamente.</p></div></>}
          <button onClick={()=>sM(null)} style={{width:"100%",padding:6,fontSize:12,color:C.tx3,background:"none",border:"none",cursor:"pointer"}}>Cerrar</button>
        </div>
      </div>}
    </div>
  </div>);
}
